name: Native build
on:
  push:
    branches: [ "graalvm-native-test" ]
jobs:
  build:
    name: ha-cli on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle Wrapper
        run: ./gradlew nativeBuild

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ha-cli-${{ matrix.os }}
          path: lib/build/native/nativeCompile/*
